[package]
name = "two_d_color_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.2"
prismatic_color = { git = "https://github.com/digitalgreenery/prismatic-color.git" }
